### ISSUE TITLE
编译调用c库的错误都还在

### ISSUE THREAD

**Issue by Angluca** [hshq/harelang#10]
#### 用你的 harec/hare 在本机测试
我也是老机器```MacBook Pro (Retina, 13-inch, Late 2013)``` ```macOS Big Sur 11.7.10```
老机器最多升级到osx 11.7, osx11以后的版本 加sudo也不能添加和修改/tmp /Volumes这些系统级的地方

* 用hello world 直接就能编译测试```hare build -lc main.ha```, 编译失败 提示需要-Wl,-no_pie
```zsh
To fix this warning, don't compile with -mdynamic-no-pic or link with -Wl,-no_pie
final section layout:
    __TEXT/__text addr=0x10000139A, size=0x0005A886, fileOffset=0x0000139A, type=1
    __TEXT/__stubs addr=0x10005BC20, size=0x00000054, fileOffset=0x0005BC20, type=29
    ... ...
ld: 32-bit RIP relative reference out of range (-4294992379 max is +/-2GB): from _main (0x1000061DF) to _environ@0x00000000 (0x00000000) in '_main' ...
```
* 上面编译失败的问题 在cc.sh里加上 这段```-Wl,-no_pie``` 就可以解决 
```zsh
 -Wl,--no-gc-sections)
            args="$args -Wl,-no_pie"
            ;;
```
* 解决上面的问题, 继续编译 新的错误提示 (这是缺少+libc.s, 直接编译是加不了include的, 而且加了还是这个 错误)
```zsh
duplicate symbol '___test_array_start' in:
    .../T/start+libc-a41dce.o
.../Hares/_hare/src/hare/stdlib/rt/6e987e1c9a48ab7f5d4200af30e91284ef97f1e0837a6a18d66e85538de0ba7d.o
duplicate symbol '___libc_init_array_start' in:
    .../T/start+libc-a41dce.o
 .../Hares/_hare/src/hare/stdlib/rt/6e987e1c9a48ab7f5d4200af30e91284ef97f1e0837a6a18d66e85538de0ba7d.o
duplicate symbol '___fini_array_start' in:
  ... ...
```
* 你说要 makefile里加include 也试了, 同样编译失败, 因为config.mk里都是 ```ld/as/qbe  = ./rt/...``` 之后我把config.mk的 全改成了```ld = $(HAREC_SRC)/rt/....```完整地址 同样是上面的```___test_array_start ...```错误
```zsh
# include $(HAREC_SRC)/config.mk
# LIBS=-lc -lSDL2_image -lSDL2_mixer -lSDL2
make
hare build -lc -lSDL2_image -lSDL2_mixer -lSDL2 cmd/demo
2/100 tasks completed (2%)Error: Command not found: ./rt/+darwin/qbe.sh
```
* 后面我都加上我之前用的+libc.s 还是全出错
```
hare build -lc
0/1 tasks completed (0%)
ld: illegal text-relocation to '_environ' in /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libc.tbd from '_main' in /Users/Angluca/.cache/hare/Users/Angluca/SDK/Hares/_hare/src/hare/stdlib/rt/6e987e1c9a48ab7f5d4200af30e91284ef97f1e0837a6a18d66e85538de0ba7d.o for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by hshq** [comment]
现在说构建问题。

我花时间做了比较大的调整，那些脚本放到系统 `PATH` 中，不再依赖 `HAREC_SRC`，
见 `.builds/darwin.yml` 和 `README.darwin`；
`hare-sdl2/Makefile` 也不再需要引入 `../hare.git/config.mk`，只需定义 `export QBE=hare-qbe.sh`。

三个项目都有改动，更新代码后先 `hare cache -c`，当然这个依赖 `$HARECACHE`。
希望这样之后不再出现类似的构建问题，至少，构建过程会少了很多配置步骤，
出现问题后也应该容易处理些。

**Comment by hshq** [comment]
`hare-arch.sh` 是软连接，参考 `.builds/darwin.yml`：
<img width="338" alt="截屏2024-03-15 15 12 17" src="https://github.com/hshq/harelang/assets/32267/c557caf6-1b38-48a9-bc7c-b62c6db42fa3">

**Comment by hshq** [comment]
[.builds/darwin.yml](https://github.com/hshq/harelang/blob/master/.builds/darwin.yml) 是个配置文件，记录了执行命令，
我也没用过，照着别的系统改的，可能是自动化构建、测试、部署用的，
所以命令和和依赖写里边，照着做就行。
