### ISSUE TITLE
darwin不需要设置TMPDIR和XDG_CACHE_HOME

### ISSUE THREAD

**Issue by Angluca** [hshq/harelang#7]
# macos 
* TMPDIR系统默认就在```/var/folders/...```一个文件夹里, 重起就会自动清除, 所以建议不修改
* XDG_CACHE_HOME也不用设置 为空时系统默认缓存文件夹就在```~/.cache```, 如果改成$HARECACHE其它工具的 cache可能会存到你的HARECACHE文件夹里 造成多余的文件
```zsh
# 只需要这3个变量就可以了 已测试, 目前我的项目是这样用的
export HARECACHE=~/.cache/hare
export HAREC_SRC=.../harec
export QBE=$HAREC_SRC/rt/+darwin/qbe.sh
```

**Comment by hshq** [comment]
是的，这两项都有默认值，可以不用更改。

我更改它们有三个目的：

1. 不想在个人目录下产生那些缓存文件；
2. 调试时频繁的编译、读写大量小文件，不如使用内存盘更好吧；
3. 调试时需要方便找到编译的汇编码文件，指定固定位置更方便。

所以我用 TmpDisk 挂载了内存盘，来达成这些目的，就需要更改这些设定。

**Comment by hshq** [comment]
Mac 上不支持 --gc-sections ，这方面我了解不多；我是在 Makefile 里把这个选项注释掉了。
我没用 hare 编译过外部库。`cmd/hare/build/util.ha`中也有这些选项，编译 hare 本身时，我在 Makefile 中指定了 LD 用 harec 中的 ld.sh 脚本，其中会去掉不支持的选项。
你可以试试也修改这些设定，或者直接删掉代码里的那些选项，重新编译 hare 。

**Comment by hshq** [comment]
这些都是 `clang` 不支持的选项，不影响构建的直接忽略了。
可以在 `$HARECACHE` 中看到记录了构建命令和错误日志文件。
`-T` 指定链接脚本，不可或缺。

编译时，把标记为 `@init`、`@fini` 和 `@test` 的函数的引用分到三类数据段里；
在链接时，链接脚本中为这三个段分别指定了 2 个符号引用其开始和结束地址，
就是那些 `___fini_array_start `，这样就可以遍历它们，分别在启动时、结束时、测试时执行。

现在汇编代码里加入上述这些符号；
加入 `qbe.sh`、`as.sh` 和 `ld.sh` 来处理不支持的选项、修改平台特定的配置和汇编代码格式。

可以在编译 `sdl2` 的日志文件中看到，它是用 `cc` 链接，所以 `ld.sh` 没起作用，
现在可以加个 `cc.sh` 来处理构建第三方库时不支持的选项，就不需要更改代码文件了；

因为这时也用了链接脚本，所以那些未定义的符号，并没有加入进来；
使用相同的办法可以解决，但带来了新的问题：
```
ld: invalid use of ADRP in '_rt.unknown_errno' to '_environ'
```
提到的代码在这里
```asm
adrp	x0, _environ@page
```
这在 `hare` 中没问题，在外部库就不行，应该是跟 `-lc` 有关，费了很久功夫，不知如何解决，
忽然想到，二者构建环境不同，可能前者生成的缓存不可用于后者，清理后就好了：
`hare cache -c`

整理下代码就提交。

**Comment by hshq** [comment]
代码提交了，
[harec](https://github.com/hshq/harelang-harec) 也有修改，
[hare-sdl2](https://github.com/hshq/hare-sdl2) 只是改了 `Makefile` 和 `EADME.md`。

**Comment by hshq** [comment]
我看了你的代码。首先，比较抱歉的是，我的 `x86_64` mbp 太老了，`homebrew` 基本上处于不可用状态，所以没法安装 `sdl2` 和大量的依赖组件进行测试。所以 `-no_pie` 选项是否在此平台必需我无法断定，只是 `aarch64` 上不需要是可以肯定的。

下面分文件谈谈我对这个项目的看法：

`README.darwin`
    我觉得可以加注释，不用改配置；
    这个文件的作用是说明和示例，所以用了我个人的配置，就像你的改动也反映了你的一样。
`util.ha`
    我的原则是尽量保持代码的兼容性，也就是可移植；
    所以主要是修改配置文件，以及 `darwin` 平台代码，与官方代码不冲突；
    所以，最好不要修改；这些配置在其他平台是必要的；
    `if (test) {` 这里的选项 "-T" 应该是 `hare` 的，而不是 `ld` 的。
`darwin.mk`
    同 `README.darwin` ；
    你这里的 `HARECACHE` 跟 `README.darwin` 中的不一致了。
`platformstart+libc.ha`
`start+aarch64+libc.s`
`start+x86_64+libc.s`
    没必要拷贝一遍；
    我已经把 `___libc_init_array_start` 这些符号用 `.include` 指令抽出去了；
    这些文件不需要的，因为一旦用了 `-lc` ，会自动添加 `+libc` 标记来构建，
    相应的也会指定入口为 `main` 函数，不再是从 `_start` 调用 `_rt.start_darwin` 了；
    这样改，可能整个改变了链接 `libc` 的运行机制，有可能不是真的 `+libc` 了，
    也有可能因为调用 `harec` 时指定了入口是 `main` 函数导致这些代码无效？
`start+libc.ha`
`start+test+libc.ha`
    去掉 `rt.envp` (引用 `environ`) 会导致依赖这个的模块和库失败吧；
    我已经通过清理缓存解决了这个问题。
